(function(){var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},n=ca(this),da=function(a,b){if(b)a:{var c=n;a=a.split(".");for(var e=0;e<a.length-1;e++){var g=a[e];if(!(g in c))break a;c=c[g]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&b!=null&&ba(c,a,{configurable:!0,writable:!0,value:b})}},p=function(a){return a.raw=a},q=function(a,b){a.raw=b;return a},t=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");},
ea=typeof Object.create=="function"?Object.create:function(a){var b=function(){};b.prototype=a;return new b},v;if(typeof Object.setPrototypeOf=="function")v=Object.setPrototypeOf;else{var w;a:{var fa={a:!0},x={};try{x.__proto__=fa;w=x.a;break a}catch(a){}w=!1}v=w?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var y=v,z=function(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(y)y(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c];a.ma=b.prototype},ha=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};
da("Promise",function(a){function b(){this.g=null}function c(d){return d instanceof g?d:new g(function(f){f(d)})}if(a)return a;b.prototype.i=function(d){if(this.g==null){this.g=[];var f=this;this.j(function(){f.o()})}this.g.push(d)};var e=n.setTimeout;b.prototype.j=function(d){e(d,0)};b.prototype.o=function(){for(;this.g&&this.g.length;){var d=this.g;this.g=[];for(var f=0;f<d.length;++f){var h=d[f];d[f]=null;try{h()}catch(k){this.l(k)}}}this.g=null};b.prototype.l=function(d){this.j(function(){throw d;
})};var g=function(d){this.i=0;this.j=void 0;this.g=[];this.H=!1;var f=this.l();try{d(f.resolve,f.reject)}catch(h){f.reject(h)}};g.prototype.l=function(){function d(k){return function(l){h||(h=!0,k.call(f,l))}}var f=this,h=!1;return{resolve:d(this.V),reject:d(this.o)}};g.prototype.V=function(d){if(d===this)this.o(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof g)this.ha(d);else{a:switch(typeof d){case "object":var f=d!=null;break a;case "function":f=!0;break a;default:f=
!1}f?this.U(d):this.v(d)}};g.prototype.U=function(d){var f=void 0;try{f=d.then}catch(h){this.o(h);return}typeof f=="function"?this.ka(f,d):this.v(d)};g.prototype.o=function(d){this.N(2,d)};g.prototype.v=function(d){this.N(1,d)};g.prototype.N=function(d,f){if(this.i!=0)throw Error("Cannot settle("+d+", "+f+"): Promise already settled in state"+this.i);this.i=d;this.j=f;this.i===2&&this.W();this.O()};g.prototype.W=function(){var d=this;e(function(){if(d.T()){var f=n.console;typeof f!=="undefined"&&
f.error(d.j)}},1)};g.prototype.T=function(){if(this.H)return!1;var d=n.CustomEvent,f=n.Event,h=n.dispatchEvent;if(typeof h==="undefined")return!0;typeof d==="function"?d=new d("unhandledrejection",{cancelable:!0}):typeof f==="function"?d=new f("unhandledrejection",{cancelable:!0}):(d=n.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.j;return h(d)};g.prototype.O=function(){if(this.g!=null){for(var d=0;d<this.g.length;++d)u.i(this.g[d]);
this.g=null}};var u=new b;g.prototype.ha=function(d){var f=this.l();d.s(f.resolve,f.reject)};g.prototype.ka=function(d,f){var h=this.l();try{d.call(f,h.resolve,h.reject)}catch(k){h.reject(k)}};g.prototype.then=function(d,f){function h(m,r){return typeof m=="function"?function(H){try{k(m(H))}catch(I){l(I)}}:r}var k,l,J=new g(function(m,r){k=m;l=r});this.s(h(d,k),h(f,l));return J};g.prototype.catch=function(d){return this.then(void 0,d)};g.prototype.s=function(d,f){function h(){switch(k.i){case 1:d(k.j);
break;case 2:f(k.j);break;default:throw Error("Unexpected state: "+k.i);}}var k=this;this.g==null?u.i(h):this.g.push(h);this.H=!0};g.resolve=c;g.reject=function(d){return new g(function(f,h){h(d)})};g.race=function(d){return new g(function(f,h){for(var k=t(d),l=k.next();!l.done;l=k.next())c(l.value).s(f,h)})};g.all=function(d){var f=t(d),h=f.next();return h.done?c([]):new g(function(k,l){function J(H){return function(I){m[H]=I;r--;r==0&&k(m)}}var m=[],r=0;do m.push(void 0),r++,c(h.value).s(J(m.length-
1),l),h=f.next();while(!h.done)})};return g});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var A=this||self,B=function(a,b){function c(){}c.prototype=b.prototype;a.ma=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.na=function(e,g,u){for(var d=Array(arguments.length-2),f=2;f<arguments.length;f++)d[f-2]=arguments[f];return b.prototype[g].apply(e,d)}},C=function(a){return a};var D=function(a){this.g=a};function E(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,E);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)}B(E,Error);E.prototype.name="CustomError";function F(a,b){a=a.split("%s");for(var c="",e=a.length-1,g=0;g<e;g++)c+=a[g]+(g<b.length?b[g]:"%s");E.call(this,c+a[e])}B(F,E);F.prototype.name="AssertionError";var G=function(a,b,c){if(!a){var e="Assertion failed";if(b){e+=": "+b;var g=Array.prototype.slice.call(arguments,2)}throw new F(""+e,g||[]);}},ia=function(a,b){throw new F("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var ja="closure_listenable_"+(Math.random()*1E6|0);var K=function(a){this.g=a};z(K,D);K.prototype[ja]=!0;var L=function(a){this.g=a};z(L,K);var M=function(a,b){this.g=a;this.i=b||null};z(M,D);M.prototype.then=function(a,b,c){var e;a&&(e=ka(this,a));this.g.aa(e,b,c)};var ka=function(a,b){var c=a.i;return c?function(e){b.call(this,new c(e))}:b};var la=[];var N=function(a){this.g=a||gbar.a;this.j=this.i=null};z(N,D);var ma=function(){var a=O();a.i||(a.i=new M(a.g.bf(),L));return a.i},na=function(){var a=O();a.j||(a.j=new M(a.g.bh()));return a.j},O=function(){G(!Object.isSealed(N),"Cannot use getInstance() with a sealed constructor.");var a="u";if(N.u&&N.hasOwnProperty(a))a=N.u;else{la.push(N);var b=new N;N.u=b;G(N.hasOwnProperty(a),"Could not instantiate singleton.");a=b}return a};var P;var Q={},R=function(a,b){if(b!==Q)throw Error("TrustedResourceUrl is not meant to be built directly");this.g=a};R.prototype.toString=function(){return this.g+""};var S=function(a){if(P===void 0){var b=null;var c=A.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:C,createScript:C,createScriptURL:C})}catch(e){A.console&&A.console.error(e.message)}P=b}else P=b}a=(b=P)?b.createScriptURL(a):a;return new R(a,Q)};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var oa=p([""]),pa=q(["\x00"],["\\0"]),qa=q(["\n"],["\\n"]),ra=q(["\x00"],["\\u0000"]),sa=p([""]),ta=q(["\x00"],["\\0"]),ua=q(["\n"],["\\n"]),va=q(["\x00"],["\\u0000"]);function T(a){return Object.isFrozen(a)&&Object.isFrozen(a.raw)}function U(a){return a.toString().indexOf("`")===-1}var wa=U(function(a){return a(oa)})||U(function(a){return a(pa)})||U(function(a){return a(qa)})||U(function(a){return a(ra)}),xa=T(sa)&&T(ta)&&T(ua)&&T(va);var ya={};function za(){if(ya!==ya)throw Error("Bad secret");};var V=function(a){za();this.g=a};V.prototype.toString=function(){return this.g};new V("about:blank");new V("about:invalid#zClosurez");var Aa=[],Ba=function(a){console.warn("A URL with content '"+a+"' was sanitized away.")};Aa.indexOf(Ba)===-1&&Aa.push(Ba);var Ca=function(){za()};Ca.prototype.toString=function(){return""};new Ca;var Da={},Ea=function(){if(Da!==Da)throw Error("SafeStyleSheet is not meant to be built directly");};Ea.prototype.toString=function(){return"".toString()};new Ea;function Fa(a){var b=ha.apply(1,arguments);if(!Array.isArray(a)||!Array.isArray(a.raw)||a.length!==a.raw.length||!wa&&a===a.raw||!(wa&&!xa||T(a))||b.length+1!==a.length)throw new TypeError("\n    ############################## ERROR ##############################\n\n    It looks like you are trying to call a template tag function (fn`...`)\n    using the normal function syntax (fn(...)), which is not supported.\n\n    The functions in the safevalues library are not designed to be called\n    like normal functions, and doing so invalidates the security guarantees\n    that safevalues provides.\n\n    If you are stuck and not sure how to proceed, please reach out to us\n    instead through:\n     - go/ise-hardening-yaqs (preferred) // LINE-INTERNAL\n     - g/ise-hardening // LINE-INTERNAL\n     - https://github.com/google/safevalues/issues\n\n    ############################## ERROR ##############################");
if(b.length===0)return S(a[0]);var c=a[0].toLowerCase();if(/^data:/.test(c))throw Error("Data URLs cannot have expressions in the template literal input.");if(/^https:\/\//.test(c)||/^\/\//.test(c)){var e=c.indexOf("//")+2;var g=c.indexOf("/",e);if(g<=e)throw Error("Can't interpolate data in a url's origin, Please make sure to fully specify the origin, terminated with '/'.");e=c.substring(e,g);if(!/^[0-9a-z.:-]+$/i.test(e))throw Error("The origin contains unsupported characters.");if(!/^[^:]*(:[0-9]+)?$/i.test(e))throw Error("Invalid port number.");
if(!/(^|\.)[a-z][^.]*$/i.test(e))throw Error("The top-level domain must start with a letter.");e=!0}else e=!1;if(!e)if(/^\//.test(c))if(c==="/"||c.length>1&&c[1]!=="/"&&c[1]!=="\\")e=!0;else throw Error("The path start in the url is invalid.");else e=!1;if(!(e=e||RegExp("^[^:\\s\\\\/]+/").test(c)))if(/^about:blank/.test(c)){if(c!=="about:blank"&&!/^about:blank#/.test(c))throw Error("The about url is invalid.");e=!0}else e=!1;if(!e)throw Error("Trying to interpolate expressions in an unsupported url format.");
c=a[0];for(e=0;e<b.length;e++)c+=encodeURIComponent(b[e])+a[e+1];return S(c)};var Ga=p(["https://accounts.google.com/gsi/client"]),Ha=p(["https://apis.google.com/js/client.js"]);function W(){window.performance.mark("gapi_load_end");window.performance.measure("gapi_load","gapi_load_start","gapi_load_end");Ia?(Ja=!0,Ka&&X()):X()}
var X,Y=null,Z=window,La=Z.colabExperiments&&Z.colabExperiments.gis_auth,Ma=Z.colabExperiments&&Z.colabExperiments.first_party_auth,Na=Z.colabExperiments&&Z.colabExperiments.rt,Ia=La&&(!Ma||Na),Ka=!1,Ja=!1,Oa=document.getElementsByTagName("script")[0],Pa=Fa(Ga);
function Qa(){if(Y)return Y;window.performance.mark("gapi_load_start");return Y=new Promise(function(a,b){X=a;Ia&&Ra(function(){b(Error("Error loading "+Pa))});if(Ma&&typeof gbar!=="undefined")na().then(function(){La?gapi.load("client",W):gapi.load("auth:client",W)}),ma().then(function(e){var g=document.documentElement.getAttribute("theme")==="dark";g&&(e.g.pp(g),e.g.pd("transparent"))});else{Z.gapi_onload=W;var c=Fa(Ha);Sa({src:c,onerror:function(){b(Error("Error loading "+c))}})}})}
function Ra(a){Sa({src:Pa,onload:function(){Ka=!0;Ja&&X()},onerror:a})}
function Sa(a){var b=document;var c="SCRIPT";b.contentType==="application/xhtml+xml"&&(c=c.toLowerCase());c=b.createElement(c);b=a.src;if(b instanceof R&&b.constructor===R)b=b.g;else{var e=typeof b;ia("expected object of type TrustedResourceUrl, got '%s' of type %s",b,e!="object"?e:b?Array.isArray(b)?"array":e:"null");b="type_error:TrustedResourceUrl"}c.src=b;var g,u;(g=(b=(u=(g=(c.ownerDocument&&c.ownerDocument.defaultView||window).document).querySelector)==null?void 0:u.call(g,"script[nonce]"))?
b.nonce||b.getAttribute("nonce")||"":"")&&c.setAttribute("nonce",g);c.async=!0;a.onload&&(c.onload=a.onload);a.onerror&&(c.onerror=a.onerror);Oa.parentNode.insertBefore(c,Oa)}Z.colab_gapi_loader={load:Qa};Qa().then(function(){},function(){});}).call(this);
